<a href="https://colab.research.google.com/github/wrixd/code/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3],dtype='int8')
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0,6.5]])
print(b)

[list([9.0, 8.0, 7.0]) list([6.0, 5.0, 4.0, 6.5])]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


In [4]:
#itemsize
a.itemsize,b.itemsize


(1, 8)

In [5]:
#no of elements
a.size,b.size

(3, 2)

In [6]:
#total size
a.size*a.itemsize,b.size*b.itemsize

(3, 16)

In [7]:
a.nbytes,b.nbytes


(3, 16)

In [8]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [9]:
a[1,5]

13

In [10]:
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [11]:
a[0,1:-1:4]

array([2, 6])

In [12]:
a[0,3]=87.32
print(a)

[[ 1  2  3 87  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [13]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [14]:
b[1,0,1]

6

In [15]:
a= np.full([2,2],534.3,dtype='float32')
print(a)

[[534.3 534.3]
 [534.3 534.3]]


In [16]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [18]:
np.random.rand(4,2)

array([[0.65171361, 0.66027321],
       [0.87258308, 0.65094924],
       [0.66516164, 0.50780702],
       [0.34115603, 0.95922471]])

In [19]:
np.random.randint(-4,8, size=(3,3))

array([[ 7,  4, -2],
       [ 0,  5, -3],
       [-2,  7, -4]])

In [21]:
output = np.zeros((5,5))
print(output)

z = np.ones((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 9. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 9. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [36]:
a=np.array([5,4,3,23,23,3],dtype='float32')
#b=a
b=a.copy()
b[2]=1021
print(a)
print(b)

[ 5.  4.  3. 23. 23.  3.]
[   5.    4. 1021.   23.   23.    3.]


In [34]:
a+2

array([ 7,  6,  5, 25, 25,  5], dtype=int32)

In [35]:
a/2

array([ 2.5,  2. ,  1.5, 11.5, 11.5,  1.5])

In [38]:
a**a

array([3.1250000e+03, 2.5600000e+02, 2.7000000e+01, 2.0880468e+31,
       2.0880468e+31, 2.7000000e+01], dtype=float32)

In [40]:
a/=a
print(a)

[1. 1. 1. 1. 1. 1.]


In [41]:
np.sin(a)

array([0.841471, 0.841471, 0.841471, 0.841471, 0.841471, 0.841471],
      dtype=float32)

In [43]:
a*(np.pi)

array([3.1415927, 3.1415927, 3.1415927, 3.1415927, 3.1415927, 3.1415927],
      dtype=float32)

In [44]:
np.sin(a),np.cos(a),np.tan(a)

(array([0.841471, 0.841471, 0.841471, 0.841471, 0.841471, 0.841471],
       dtype=float32),
 array([0.5403023, 0.5403023, 0.5403023, 0.5403023, 0.5403023, 0.5403023],
       dtype=float32),
 array([1.5574077, 1.5574077, 1.5574077, 1.5574077, 1.5574077, 1.5574077],
       dtype=float32))